server:
  port: 9000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/oauth2
    username: root
    password: root!@@&
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: false
      enabled: false # 首次执行时通过 -Dsql.init.enabled=true 来开启
      encoding: utf-8
      schema-locations:
        - classpath:META-INF/oauth2.sql
  #      data-locations:
  #        - classpath:META-INF/oauth2-data.sql
  redis:
    host: 127.0.0.1
    password: tvoc.site.redis
  security:
    oauth2:
      client:
        registration:
          dingtalk:
            client-id: dingopfniakkw72klkjv
            client-secret: 6Il0DuPZPPIr-OG03uMrnqDNu_o03tpIkK03ScpuEPP6NAw7J52D0LWPvTjRf4BR
          github:
            client-id: db3bd3536a1d3163acf9
            client-secret: f7170889aefcb05ed1c5b316c08c00eb5c315374
#          test:
#            provider: native
#            client-id: demo
#            client-secret: "{noop}123456"
mybatis-plus:
  global-config:
    banner: false
api:
  result:
    code-as-number: true
