version: "3.1"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${BASE_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${BASE_PATH}/nginx/logs:/var/log/nginx
      - ${BASE_PATH}/nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - 8188:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${BASE_PATH}/redis/redis.conf:/conf/redis.conf
      - ${BASE_PATH}/redis/data:/data
    command: redis-server /conf/redis.conf
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
     - 8189:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ${BASE_PATH}/mongo/data:/data/db
