CREATE TABLE oauth2_provider_account
(
  ID         VARCHAR(32) NOT NULL COMMENT '主键',
  ACCOUNT_ID VARCHAR(32) NOT NULL COMMENT '账号 ID',
  PROVIDER   VARCHAR(64) NOT NULL COMMENT '认证提供商',
  CLIENT_ID  VARCHAR(64) NOT NULL COMMENT '认证提供商内应用 ID',
  UNION_ID   VARCHAR(64) NOT NULL COMMENT '用户在认证提供商的唯一 ID',
  OPEN_ID    VARCHAR(64) NOT NULL COMMENT '用户在应用内唯一 ID',
  CREATED_AT DATETIME(6) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (ID)
) COMMENT = '认证提供商账号';


CREATE UNIQUE INDEX UK_TUO ON oauth2_provider_account (PROVIDER, CLIENT_ID, UNION_ID, OPEN_ID);
CREATE INDEX IDX_ACCOUNT ON oauth2_provider_account (ACCOUNT_ID);

CREATE TABLE oauth2_account
(
  ID         VARCHAR(32) NOT NULL COMMENT '用户 ID',
  USERNAME   VARCHAR(64) NOT NULL COMMENT '用户名',
  PASSWORD   VARCHAR(128) COMMENT '密码',
  JOB_NUMBER VARCHAR(32) COMMENT '工号',
  REAL_NAME  VARCHAR(32) COMMENT '真实姓名',
  MOBILE     VARCHAR(11) NOT NULL COMMENT '手机',
  EMAIL      VARCHAR(64) COMMENT '邮箱',
  AVATAR     VARCHAR(128) COMMENT '头像',
  STATUS     INT(2) COMMENT '状态',
  CREATED_BY VARCHAR(32) COMMENT '创建人',
  CREATED_AT DATETIME(6) COMMENT '创建时间',
  UPDATED_BY VARCHAR(32) COMMENT '更新人',
  UPDATED_AT DATETIME(6) COMMENT '更新时间',
  PRIMARY KEY (ID)
) COMMENT = '账号';


CREATE UNIQUE INDEX UK_USERNAME ON oauth2_account (USERNAME);
CREATE UNIQUE INDEX UK_JOB_NUMBER ON oauth2_account (JOB_NUMBER);
CREATE UNIQUE INDEX UK_MOBILE ON oauth2_account (MOBILE);
CREATE INDEX UK_EMAIL ON oauth2_account (EMAIL);

CREATE TABLE oauth2_client
(
  ID                            VARCHAR(32) NOT NULL COMMENT '主键',
  REGISTRATION_ID               VARCHAR(64) COMMENT '注册 ID',
  PROVIDER                      VARCHAR(64) COMMENT '认证提供商',
  CLIENT_ID                     VARCHAR(32) NOT NULL COMMENT '客户端 ID',
  CLIENT_ID_ISSUED_AT           DATETIME(6) NOT NULL COMMENT '客户端注册时间',
  CLIENT_SECRET                 VARCHAR(64) COMMENT '客户端密钥',
  CLIENT_SECRET_EXPIRES_AT      DATETIME(6) COMMENT '客户端密钥过期时间',
  CLIENT_NAME                   VARCHAR(32) NOT NULL COMMENT '客户端名称',
  CLIENT_AUTHENTICATION_METHODS INT         NOT NULL COMMENT '客户端认证方法',
  AUTHORIZATION_GRANT_TYPES     INT         NOT NULL COMMENT '授权类型',
  REDIRECT_URIS                 VARCHAR(128) COMMENT '重定向地址',
  SCOPES                        TEXT        NOT NULL COMMENT '允许授予的权限',
  CLIENT_SETTINGS               TEXT        NOT NULL COMMENT '客户端设置',
  TOKEN_SETTINGS                TEXT        NOT NULL COMMENT '令牌设置',
  PRIMARY KEY (ID)
) COMMENT = '客户端';


CREATE UNIQUE INDEX UK_CID ON oauth2_client (CLIENT_ID);
CREATE UNIQUE INDEX UK_CRID ON oauth2_client (REGISTRATION_ID);

CREATE TABLE oauth2_authorization2
(
  ID                       VARCHAR(32) NOT NULL COMMENT '主键',
  REGISTERED_CLIENT_ID     VARCHAR(32) NOT NULL COMMENT '注册的客户端 ID',
  PRINCIPAL_NAME           VARCHAR(64) NOT NULL COMMENT '授权主体名称',
  AUTHORIZATION_GRANT_TYPE VARCHAR(64) NOT NULL COMMENT '授权类型',
  AUTHORIZED_SCOPES        TEXT        NOT NULL COMMENT '实际授予的权限',
  ATTRIBUTES               TEXT COMMENT '',
  PRIMARY KEY (ID)
) COMMENT = '授权';


CREATE UNIQUE INDEX UK_RCI_PN ON oauth2_authorization2 (REGISTERED_CLIENT_ID, PRINCIPAL_NAME);

CREATE TABLE oauth2_authorization_code
(
  ID            VARCHAR(32) NOT NULL COMMENT '主键',
  AUTHORIZED_ID VARCHAR(32) NOT NULL COMMENT '授权 ID',
  CODE          VARCHAR(64) NOT NULL COMMENT '授权码',
  STATE         VARCHAR(64) COMMENT '防止重放攻击参数',
  ISSUED_AT     DATETIME(6) COMMENT '签发时间',
  EXPIRES_AT    DATETIME(6) COMMENT '过期时间',
  METADATA      TEXT COMMENT '元数据',
  PRIMARY KEY (ID)
) COMMENT = '授权码';

CREATE TABLE oauth2_access_token
(
  ID                VARCHAR(32) NOT NULL COMMENT '主键',
  AUTHORIZED_ID     VARCHAR(32) NOT NULL COMMENT '授权 ID',
  ACCESS_TOKEN      TEXT        NOT NULL COMMENT '访问令牌',
  ACCESS_TOKEN_TYPE VARCHAR(64) COMMENT '访问令牌类型',
  ISSUED_AT         DATETIME(6) COMMENT '签发时间',
  EXPIRES_AT        DATETIME(6) COMMENT '过期时间',
  METADATA          TEXT COMMENT '元数据',
  PRIMARY KEY (ID)
) COMMENT = '访问令牌';

CREATE TABLE oauth2_refresh_token
(
  ID            VARCHAR(32) NOT NULL COMMENT '主键',
  AUTHORIZED_ID VARCHAR(32) NOT NULL COMMENT '授权 ID',
  REFRESH_TOKEN TEXT        NOT NULL COMMENT '刷新令牌',
  ISSUED_AT     DATETIME(6) COMMENT '签发时间',
  EXPIRES_AT    DATETIME(6) COMMENT '过期时间',
  METADATA      TEXT COMMENT '元数据',
  PRIMARY KEY (ID)
) COMMENT = '刷新令牌';

CREATE TABLE oauth2_oidc
(
  ID            VARCHAR(32) NOT NULL COMMENT '主键',
  AUTHORIZED_ID VARCHAR(32) NOT NULL COMMENT '授权 ID',
  ID_TOKEN      TEXT        NOT NULL COMMENT '身份令牌',
  ISSUED_AT     DATETIME(6) COMMENT '签发时间',
  EXPIRES_AT    DATETIME(6) COMMENT '过期时间',
  METADATA      TEXT COMMENT '元数据',
  PRIMARY KEY (ID)
) COMMENT = '身份令牌';

