version: "3.1"
services:
  redis:
    container_name: redis
    image: redis:6.2.2
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /d/home/data/docker/redis/redis.conf:/conf/redis.conf
      - /d/home/data/docker/redis/data:/data
    command: redis-server /conf/redis.conf
  mongo:
    container_name: mongo
    image: mongo:4.4.5
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /d/home/data/docker/mongo/data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
