spring:
  application:
    name: 演示项目
    version: 1.0.0
  redis:
    database: 7
    host: tvoc.site
    password: tvoc.redis
    port: 8188
  data:
    mongodb:
#      uri: mongodb://backend:backend@tvoc.site:8189/backend?authSource=admin
      host: tvoc.site
      port: 8189
      database: backend
      username: backend
      password: backend
      authentication-database: admin
  cache:
    #    type: caffeine
    redis:
      time-to-live: 2h
#      cache-null-values: false
#      enable-statistics: true
#    caffeine:
#      time-to-live: 10s
api:
  json:
    automatic-wrapped: true
#    result:
#      success: succeed
#      code: status
#      message: msg
  system:
    prefix: sys
#debug: true
logging:
  level:
    root: info
