# 1. 授权码流程
# 1.1 获取授权码 浏览器打开以下地址 redirect_url 不能使用 localhost
GET http://localhost:9000/oauth2/authorize?client_id=csdn&response_type=code&scope=message.read&redirect_uri=http://127.0.0.1:8090/callback

###
# 1.2 根据授权码获取 token
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id=csdn&client_secret=csdn123&grant_type=authorization_code&code=zZE9awMTlTUuJw7EaoUPTtIqei9z1gyqCVEnC39FI0fCTap16kpxEMm_1oU-oOw8YILyYvLrmxhQs5Ale6bjdjm273fmgZuLntD4AxkJrRYHcmFLtcmauBgg1zFHfCV3&redirect_uri=http://127.0.0.1:8090/callback

###
# 2. 根据刷新令牌获取token
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id=csdn&client_secret=csdn123&grant_type=refresh_token&refresh_token=22403a300a2219f8402294dc98183967e1b6b97d334180b1ef76c4aecfe15375

###
# 3. 客户端凭证(此模式下，没有用户的参与，只有客户端和授权服务器之间的参与)
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id=csdn&client_secret=csdn123&grant_type=client_credentials

###
# 4. 密码式
POST http://localhost:9000/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id=csdn&grant_type=password&username=demo&password=123456

###
# 4. 撤销令牌
POST http://localhost:9000/oauth2/revoke
Authorization: Basic Y3Nkbjpjc2RuMTIz
Content-Type: application/x-www-form-urlencoded

token=1e82dec49250af4b8a0d041144770e1e750c122663a576dd3c751ff1996268c7

###
# 5. 查看 token 的信息（令牌内省）
POST http://localhost:9000/oauth2/introspect
Authorization: Basic Y3Nkbjpjc2RuMTIz
Content-Type: application/x-www-form-urlencoded

token=91b3003c1d5baa7716b1823a34657ff8cd154c13c3f593de7b8a236aaaa6095d


###
# 6. 查看JWK信息
GET http://localhost:9000/oauth2/jwks
