server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-exception: true
    include-binding-errors: always
spring:
  application:
    name: API Platform
    version: 1.0
  profiles:
    active: local
logging:
  level:
    root: warn
    com.voc: warn
    org.springframework.web: warn
    org.springframework.security: warn
    org.springframework.security.oauth2: warn
api:
#  API 前缀
  prefix: /api
