server:
  port: 8080
spring:
  application:
    name: API Platform
    version: 1.0
  profiles:
    active: local
logging:
  level:
    root: warn
    com:
      voc: warn
      baomidou: warn
      alibaba: warn
api:
#  API 前缀
  prefix: /api
